name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker-compose up -d
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: localhost:5000
          username: testuser
          password: testpassword
      - run: ./.github/scripts/create_test_tags.sh
      - run: |
          npm install
      - run: |
          npm run all
      - run: docker-compose down
        if: always()
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker-compose up -d
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: localhost:5000
          username: testuser
          password: testpassword
      - run: ./.github/scripts/create_test_tags.sh
      - uses: ./
        with:
          registry: http://localhost:5000
          username: testuser
          password: testpassword
          repository: test
      - run: docker-compose down
        if: always()
